fix: code language compatible with special char (fix #1352)
vuejs/vitepress pull request #1353
Opened 2022-09-17 15:33 UTC by sun0day

Code block's `language-` class should  compatible with special char, such as '-', '+', '#'...

After PR:

```
"language-" => "language- line-numbers-mode"
"language-js" => "language-js line-numbers-mode"
"language-c#" => "language-c# line-numbers-mode"
"language-c++" => "language-c++ line-numbers-mode"
"language-Objective-C" => "language-Objective-C line-numbers-mode"
"language-js xxxx" => "language-js xxxx line-numbers-mode"
```

2022-09-17 15:40 UTC, brc-dd requested changes
This won't work with string like this:

```html
<div class="language-">..."...</div>
```

Probably something like `/"(language-[^\s"]*?)"/` should work

2022-09-17 15:50 UTC, sun0day commented
use `/"(language-.*?)"/` ?

`/"(language-[^\s"]*?)"/` dont work with `<div class="language-    xxxx">..."...</div>`

2022-09-17 15:53 UTC, brc-dd commented
There won't be any `<div class="language- xxxx">..."...</div>` case if that div is generated by our code highlighting plugin.

2022-09-17 15:59 UTC, sun0day commented
> There won't be any `<div class="language- xxxx">..."...</div>` case if that div is generated by our code highlighting plugin.

From the current code, yes, this case won't happen.

But what I concern is that from the `lineNumberPlugin` API aspect, it is better to be compatible with more cases

2022-09-18 19:19 UTC, brc-dd commented
Change it to either. I'd still recommend `\S` one, we should keep regexes stricter because they tend to mess back 😅. However, in this case both should work fine IG.

2022-09-19 03:21 UTC, sun0day commented
> Change it to either. I'd still recommend `\S` one, we should keep regexes stricter because they tend to mess back 😅. However, in this case both should work fine IG.

Alright. Let's change it to `/"(language-\S*?)"/` for now.

Done. Merge it at your convenience. @brc-dd

2022-09-19 04:06 UTC, brc-dd approved these changes

2022-09-19 04:08 UTC, merged