fix: resolve page hash case-insenstively, close #202
vuejs/vitepress pull request #203
Opened 2021-01-08 16:14 UTC by antfu

2021-01-08 16:15 UTC, antfu commented
@knightly-bot build this

2021-01-08 22:19 UTC, yyx990803 requested changes
I think it's better to directly enforce lowercase entry names [here](https://github.com/vuejs/vitepress/blob/master/src/node/build/bundle.ts#L31).

2021-01-10 05:12 UTC, antfu commented
See #202. In Netlify, every url is case-insensitive, which means `/assets/a.js` will be exactly the same as `/assets/A.js`. The problem here is that the hashMap resolving is case-sensitive. For example

```js
const pageToHashMap = {
  hello: '123456789'
}

const hash = pageToHashMap['Hello'] // undefined
const url = `/a.${hash}.js` // /a.undefined.js
```

![image](https://user-images.githubusercontent.com/11247099/104114948-06640880-5345-11eb-84c9-b48032c80a19.png)


Forcing to generate lowercase output as you suggested might be a good addition but I guess it's not really related to fixing the issue. (or did I misunderstand anything?)

Thanks.

2021-01-11 00:23 UTC, yyx990803 approved these changes

2021-01-11 00:24 UTC, merged