fix: HomeHero NavLink reactivity lost.
vuejs/vitepress pull request #212
Opened 2021-01-23 17:09 UTC by ShenQingchuan

Please see https://github.com/vuejs/vitepress/issues/195 for more details... (May Chinese required)

2021-01-23 17:15 UTC, ShenQingchuan commented
# Something Weird

For the code below:
```typescript
const props = defineProps<{
  item: DefaultTheme.NavItemWithLink,
}>();
const propsRefs = toRefs(props);
const { props: linkProps, isExternal } = useNavLink(propsRefs.item);
```

It seems very tedious, right?
but when I changed it to this:
```typescript
const propsRefs = toRefs(defineProps<{
  item: DefaultTheme.NavItemWithLink,
}>());
const { props: linkProps, isExternal } = useNavLink(propsRefs.item);
```

the JS Console print this:

![image](https://user-images.githubusercontent.com/46062972/105609053-94c69880-5de1-11eb-8f58-8ccfec0b3217.png)

May this be a new bug or something wrong with my code ?

2021-02-10 14:16 UTC, kiaking requested changes
Thank you so much for the PR! I've left a comment so please have a look. I think we only need to change `NavLink.vue` with this change.

2021-02-10 14:16 UTC, kiaking commented on src/client/theme-default/components/NavLink.vue
> +const { props: linkProps, isExternal } = useNavLink(propsRefs.item);
I think we only need to stop destructuring. So following should work. Could you test with one? It's working on my env.

```suggestion
const props = defineProps<{
  item: DefaultTheme.NavItemWithLink,
}>();

const { props: linkProps, isExternal } = useNavLink(props.item);
```

2021-02-10 14:39 UTC, ShenQingchuan commented
Yes. Without `toRefs` it still works, that's my mistake...

2021-02-10 15:55 UTC, kiaking requested changes
I don't think we need `NavDropdownLinkItem.vue ` and `navLink.ts` changes anymore. Can we delete them? 👀

2021-02-10 16:11 UTC, ShenQingchuan commented
> I don't think we need `NavDropdownLinkItem.vue ` and `navLink.ts` changes anymore. Can we delete them? 👀

Sure, I'll refactor my commits and repush later...

2021-02-10 16:57 UTC, ShenQingchuan commented
**OOPS !! @_@** @kiaking 

 `navLinks.ts` need to be changed...

**Why I need the argument `item` of `useNavLink(item)`  to be a `Ref<DefaultTheme.NavItemWithLink>`**:

Because the value you passed into in `HomeHero.vue` as `item` v-bind: 

```vue
<NavLink
  v-if="hasAction"
  :item="{ link: data.actionLink, text: data.actionText }"
  class="action"
/>
```
is **Not** a `ref` at all, when the locales changed, the data(from frontMatter info) did change, but the object itself didn't change at all, it performs as a constant object.

cut a long story short, it will show a bug when you follow these steps:
1. open a English version doc first
2. click another language locale link
3. and you can see the homehero button's text has changed, that's fine and what we expected.
4. but if you click the button, then we will still go to the English section, not the language we wanted.

2021-02-10 17:02 UTC, ShenQingchuan commented
the `item` passed it into `useNavLink` need to be a `ref`, or it will never changed... 

you can set a `watch` and write a function to `console.log(item.link)` for debuging, 

and you'll see the `item.link` string value has never changed to anthoer language (such as 'zh') `/zh/xxx` but still `/xxx`

2021-02-10 17:14 UTC, ShenQingchuan commented
I did this PR a long time ago, I just didn't remember some details, feel really embarrassed...

2021-02-11 01:29 UTC, kiaking commented
Ah good point! Yap. To note, it's not because of how we pass props, props are reactive because `item.text` is working just fine. It's about how we're passing props to the composable function. Maybe we should have made it call it from the parent component. I might refactor this later.

But for now, thank you so much for the fix!

2021-02-11 01:29 UTC, kiaking approved these changes

2021-02-11 01:30 UTC, merged