docs: fix Github Pages Action example error
vuejs/vitepress pull request #3169
Opened 2023-11-02 08:07 UTC by maicss

1, Set default node version to 20
2, Default project `package.json` doesn't have `ci` command, change it to `install`
3, Update `pnpm` block, previous not working
4, Default projet root is current dir not `docs`, change `build` and `project path` blocks. Previous config throw error `No such file or directory`

2024-03-03 06:23 UTC, AyushSehrawat commented
This pr should be merged 👍🏻 

Also not sure what's the reason to remove pnpm from comments, typo ?

![image](https://github.com/vuejs/vitepress/assets/69469790/fc75c364-0830-4cb1-97a8-8e919f575ee2)

It worked fine for me with pnpm cache

2024-07-19 09:06 UTC, cycleccc approved these changes

2024-07-23 07:51 UTC, maicss commented
> This pr should be merged 👍🏻
> 
> Also not sure what's the reason to remove pnpm from comments, typo ?
> 
> ![image](https://private-user-images.githubusercontent.com/69469790/309529971-fc75c364-0830-4cb1-97a8-8e919f575ee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjEzNTAsIm5iZiI6MTcyMTcyMTA1MCwicGF0aCI6Ii82OTQ2OTc5MC8zMDk1Mjk5NzEtZmM3NWMzNjQtMDgzMC00Y2IxLTk3YTgtOGU5MTlmNTc1ZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3NTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MDUxNmExNjBiNmQyNzg4MDRkMThmMjk4MzQ3MmVlZTcxZTgzY2E3ZWY5MGE4ZGU4MTdmYTQ4N2VmNTBmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sVkI2vurlzp3zwzkF3KDpe6bI9tfw9fKsOPAMDAIpfI)
> 
> It worked fine for me with pnpm cache

Yes, it's a typo, fixed.

2025-02-06 09:50 UTC, jankapunkt requested changes

2025-02-06 09:50 UTC, jankapunkt commented on docs/en/guide/deploy.md
>             uses: actions/configure-pages@v4
With vitepress@1.6.3 and custom URLs I get the following error when using `actions/configure-pages@v4`

```
Error: Get Pages site failed. Please verify that the repository has Pages enabled and configured to build using GitHub Actions, or consider exploring the `enablement` parameter for this action.
```

upgrading to  `actions/configure-pages@v5` resolved this

2025-02-06 09:50 UTC, jankapunkt commented on docs/en/guide/deploy.md
> +           run: npm install # or pnpm install / yarn install / bun install
Is there a reason to use npm install instead of npm ci?

If npm ci gives you troubles although locally your package lock is in sync then you likely need to disable legacy-peer-deps in ~/.npmrc on your local machine, then rm -rf node_modules and rm package-lock.json then npm install again.

see: https://stackoverflow.com/a/76400582/3098783

Might be a good addition as comment in case people struggle with this errir

2025-06-20 16:10 UTC, maicss commented on docs/en/guide/deploy.md
> +           run: npm install # or pnpm install / yarn install / bun install
Yes, you are right.

2025-06-22 18:17 UTC, maicss commented
@jankapunkt Thanks for you suggestions, I have made some changes.

2025-07-10 01:11 UTC, maicss commented
@jankapunkt Is this pr still useful to this project? It takes tow years.

2026-07-09 00:03 UTC, bluwy commented
Superseded by https://github.com/vuejs/vitepress/commit/30b323d6e7c63a9599a09c9046629ff40721a4d1

2026-07-09 00:03 UTC, closed without merging