docs(pt): Create Portuguese VitePress translation
vuejs/vitepress pull request #3531
Opened 2024-02-01 23:09 UTC by viniciusdeliz

2024-02-01 23:22 UTC, viniciusdeliz commented
@savionascimentodev your help would be of great value in here! There's a lot of English content to be translated

2024-02-01 23:37 UTC, savionascimentodev commented
You can count on me 😁

2024-02-02 13:37 UTC, viniciusdeliz commented
> You can count on me 😁

@savionascimentodev You can pick an item here from the list above and let me know here so I can update its status. If you prefer we can use the Issues inside my fork https://github.com/viniciusdeliz/vitepress/issues

2024-02-06 20:22 UTC, viniciusdeliz commented
Mentioning @brc-dd because I saw he reviewed many of the docs translation/i18n PRs.
I'd love to know if this PR is adequate  for including a Portuguese version of the VitePress docs. I'll be glad to collaborate.
Let me know if I should perform any adjustment, or if I should include any file or any change at all. Thanks!

2024-02-07 11:25 UTC, awxiaoxian2020 requested changes

2024-02-07 11:25 UTC, awxiaoxian2020 commented on docs/pt/index.md
> +      link: /guide/getting-started
```suggestion
      link: /pt/guide/getting-started
```

2024-02-08 18:50 UTC, brc-dd commented
Please update docs/lunaria.config.json too.

2024-02-08 19:39 UTC, viniciusdeliz commented
> Please update docs/lunaria.config.json too.

@brc-dd updated and running. Let me know if further adjustments are required!

2024-02-17 14:03 UTC, brc-dd commented
Hi, the ids of heading should be synced to the English version. Refer Chinese counterparts for example.

2024-02-17 18:22 UTC, viniciusdeliz commented
> Hi, the ids of heading should be synced to the English version. Refer Chinese counterparts for example.

@brc-dd I've just included the heading links in all the files. And thank you for the addition that I missed in the `lunaria.config.json`. Let me know if I missed anything else, I'll be glad to assist

2024-02-17 19:49 UTC, brc-dd commented
Thanks. I'll review this in few days.

2024-03-07 07:30 UTC, merged