修复中文的语法错误
vuejs/vitepress pull request #3679
Opened 2024-03-22 00:55 UTC by nookery

2024-03-22 03:06 UTC, awxiaoxian2020 requested changes

2024-03-22 03:06 UTC, awxiaoxian2020 commented on docs/zh/guide/mpa-mode.md
> +在 MPA 模式下，所有页面都会默认不包含任何 JavaScript。因此，站点可能从评估工具中获得更好的初始访问性能分数。
```suggestion
在 MPA 模式下，所有页面都会默认不包含任何 JavaScript。因此，站点可能在评估工具中能够获得更好的初始访问性能分数。
```

2024-04-10 02:43 UTC, meteorlxy commented on docs/zh/guide/mpa-mode.md
> +在 MPA 模式下，所有页面都会默认不包含任何 JavaScript。因此，站点可能从评估工具中获得更好的初始访问性能分数。
"可能" "能够" 感觉有点重复。把 "能够" 去掉好像也可以？

2024-04-10 02:55 UTC, meteorlxy commented
Closing via 27f8644b5f883bdfa5bc8d74ec94028ac85289cb

2024-04-10 02:55 UTC, closed without merging