feat: rendering meta tags for preview images (twitter/og)
vuejs/vitepress pull request #498
Opened 2022-01-15 21:53 UTC by jbandi

For some use-cases it might be desired to have a preview image for social media.

With this PR a preview image can be specified on site level (.viteress/config.ts) and also per page (frontmatter).

The images have to be added to `public/images`, vite is not putting them there.

2022-02-22 01:59 UTC, yyx990803 commented on docs/.vitepress/config.ts
> +  banner: './images/vite.png',
Should this be `socialImage` instead?

2022-02-22 02:00 UTC, yyx990803 requested changes

2022-02-22 02:00 UTC, yyx990803 commented on src/node/config.ts
> +  socialImage?: string
I don't think we need a site-wide config option for this, since you can already do that using `head`.

2022-06-14 07:20 UTC, kiaking commented
Closing in favor of https://github.com/vuejs/vitepress/issues/551

2022-06-14 07:20 UTC, closed without merging