feat:  add active status to navbar menu Group
vuejs/vitepress pull request #820
Opened 2022-06-20 08:56 UTC by casyalex

add active style to VPFlyout, make navbar group can show active status.

2022-06-20 09:21 UTC, kecrily requested changes

2022-06-20 09:21 UTC, kecrily commented on docs/.vitepress/config.ts
> +      items: [{ text: 'Guide', link: '/guide/what-is-vitepress', },]
The changes made during testing should be reverted.

2022-06-20 09:21 UTC, kecrily commented on src/client/theme-default/components/VPFlyout.vue
> +      @click="open = !open">
Here too it seems to be a mere change of style and they should not be modified.

2022-06-20 10:59 UTC, casyalex commented
useless change removed. Thanks

2022-06-21 15:35 UTC, kiaking commented
Thanks a lot! 🙌

2022-06-21 15:35 UTC, merged